In [1]:
## Numpy Problems

In [2]:
import numpy as np   ## Installation of Numpy

In [3]:
print(np.__version__)  ## Version of Numpy

1.24.2


0-D Array

In [4]:
arr_0 = np.array(220)
print(arr_0)

220



1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [5]:
Lst =[12.23, 13.32, 100, 36.32] 
arr = np.array(Lst)         

In [6]:
print(arr)    ## 1-D array

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [7]:
newarr = np.arange(2,11).reshape(3,3)
print(newarr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [8]:
newarr = np.zeros((10))  # Containing all zeros
print(newarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Change the 6 th element into 11
newarr[6] = 11
print(newarr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [10]:
or_arr = np.arange(12,38)
print(or_arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [11]:
revers_arr = or_arr[: :-1]
print(revers_arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output

Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]


1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]





In [12]:
orig_arr = np.ones((5,5)) #Creating a 5*5 array filled with ones
print("Original Array \n")
print(orig_arr)

Original Array 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
orig_arr[1:-1, 1:-1] = 0
print("Modifying the array with Zero")
print(orig_arr)

Modifying the array with Zero
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]


In [14]:
orig_arr = np.ones((3,3)) #Creating a 3*3 array filled with ones
print("Original Array \n")
print(orig_arr)

Original Array 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
x= np.pad(orig_arr, pad_width = 1, mode ="constant", constant_values = 0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [16]:
x = np.zeros((8,8) , dtype = int)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [17]:
x[1::2 , ::2] = 1
x[::2 , 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
y = np.zeros((8,8) , dtype = int)
y[::2 , 1::2] = 1
y[1::2 , ::2] = 1
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]


In [19]:
lst = [i for i in range(1,9)]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8]


In [20]:
# converting list to array
lst_arr = np.array(lst)
print(lst_arr)

[1 2 3 4 5 6 7 8]


In [21]:
tup = tuple(lst[::-1])
print(tup)

(8, 7, 6, 5, 4, 3, 2, 1)


In [22]:
 #converting tuples into 2-D array
tup_arr = np.array(tup).reshape(2,4)
print(tup_arr)

[[8 7 6 5]
 [4 3 2 1]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [23]:
original_arr = np.array([i for i in range(10,31,10)])
print(original_arr)

[10 20 30]


In [24]:
new_arr = np.append(original_arr,[40,50,60,70,80,90],axis=0)


In [25]:
print(new_arr)

[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [62]:
# Create an array of complex numbers
complex_array = np.array([1 + 0j, 0.70710678 + 0.70710678j])

# Print the original array
print("Original array", complex_array)

# Find the real part of the array
real_part = complex_array.real

# Find the imaginary part of the array
imaginary_part = complex_array.imag

# Print the real and imaginary parts
print("Real part of the array:", real_part)
print("Imaginary part of the array:", imaginary_part)

Original array [1.   +0.j    0.707+0.707j]
Real part of the array: [1.    0.707]
Imaginary part of the array: [0.    0.707]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements


In [63]:
from numpy import random

In [28]:
x = np.array([1,8,6,5], dtype = np.float64)
print(x)

[1. 8. 6. 5.]


In [29]:
print("Size of the array: ", x.size)

print("Length of one array element in bytes: ", x.itemsize)

print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  4
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  32


12. Write a Python program to find common values between two arrays.


In [30]:
arr_1 = np.array([0,10,20,30,50,40])
arr_2 = np.array([5,10,15,20,25,30])

arr_3 = np.intersect1d(arr_1,arr_2)
print(arr_3)

[10 20 30]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2

In [31]:
Array1 = [ 0 ,10 ,20, 40, 90, 80,100,60]
Array2 = [10, 30, 40, 50, 70, 90]

Array3 = np.setdiff1d(Array1,Array2)

In [32]:
print(Array3)

[  0  20  60  80 100]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays

In [64]:
Array1 = [ 0 ,10 ,20,     40,         90, 80, 100, 60]
Array2 = [    10,     30, 40, 50, 70, 90]

Array3 = np.setxor1d(Array1,Array2)

print(Array3)

[  0  20  30  50  60  70  80 100]


15. Write a Python program compare two arrays using numpy

In [65]:
arr1 = np.array([1,60])
arr2 = np.array([5,8])

print(arr1)
print(arr2)

print("a > b")
print(np.greater(arr1,arr2))

print("a >= b")
print(np.greater_equal(arr1,arr2))

print("a < b")
print(np.less(arr1,arr2))

print("a <= b")
print(np.less_equal(arr1,arr2))

[ 1 60]
[5 8]
a > b
[False  True]
a >= b
[False  True]
a < b
[ True False]
a <= b
[ True False]


In [67]:
x = np.arange(12).reshape(3,4)
print("Before loading in the file\n")
print(x)

header = 'col1 col2 col3'

np.savetxt('temp.txt', x ,fmt = '%d' , header = header)

print("\nAfter loading the file \n")

result = np.loadtxt('temp.txt')

print(result)

result2 = np.loadtxt('temp.txt', dtype=int)

print(result2)


Before loading in the file

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

After loading the file 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [36]:
array = np.array([[10, 20 ,30], [20 ,40 ,50]] ) .reshape(-1)

In [37]:
print(array)

[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.

In [38]:
arr = np.array([[2,4,6],[6,8,10]], dtype = np.int32)
x = arr.astype(float)

In [39]:
print(arr)

print("\n Data Type of the array :",arr.dtype)

print(x)
print("\n New Data Type of the array : " ,x.dtype)


[[ 2  4  6]
 [ 6  8 10]]

 Data Type of the array : int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]

 New Data Type of the array :  float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere

In [40]:
arr = np.eye(3)

In [41]:
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

In [70]:
up_trigular = np.tri(4,3 , -1 )

In [72]:
print(up_trigular)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.

In [44]:
a1 = np.arange(0,6).reshape(2,3)
a2 = np.arange(5,11).reshape(2,3)

print(a1)
print(a2)

[[0 1 2]
 [3 4 5]]
[[ 5  6  7]
 [ 8  9 10]]


In [45]:
arr3 = np.concatenate((a1,a2), axis=1)
print(arr3)

[[ 0  1  2  5  6  7]
 [ 3  4  5  8  9 10]]


21. Write a Python program to make an array immutable (read-only)

In [74]:

x = np.array([1, 2, 3, 4, 5])

x.flags.writeable = False

print("Test the array is read-only or not:")

try:
    x[0] = 10
except ValueError as e:
    
    print(e)


Test the array is read-only or not:
assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array

In [47]:
org = np.arange(12).reshape(3,4)
print(org)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
new = org *3
print(new)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

In [85]:
array = np.arange(6).reshape(3,2)

In [86]:
print(array)

[[0 1]
 [2 3]
 [4 5]]


In [87]:
lst = [i for i in array]

In [88]:
print(lst)

[array([0, 1]), array([2, 3]), array([4, 5])]


In [90]:
lst2 = [j for i in array for j in i]
print(lst2)

[0, 1, 2, 3, 4, 5]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

In [91]:
# Create a NumPy array
np_array = np.array([1, 2, 3, 4, 5])

# Convert the NumPy array to a Python list
python_list = np_array.tolist()

# Print the Python list
print(python_list)

[1, 2, 3, 4, 5]


In [53]:

original_array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 
                           0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])

np.set_printoptions(precision=3)


print("Array values with precision 3:")
print(original_array)


Array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array

In [54]:

original_array = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])

# Set print options to suppress scientific notation and set precision
np.set_printoptions(suppress=True, precision=3)

# Print the original array elements
print("Original array elements:")
print(original_array)

# Print the array values with specified precision
print("\nPrint array values with precision 3:")
print(original_array)


Original array elements:
[   0.       1.6   1200.       0.235]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array


In [55]:
x = np.array([[10, 20, 30], [40, 50, 60]])
print(x)

[[10 20 30]
 [40 50 60]]


In [56]:
y = np.array([[100], [200]])

In [57]:
print(np.append(x,y,axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array


In [58]:
array = np.array([i for i in range(10,101,10)])

In [59]:
print(array)

[ 10  20  30  40  50  60  70  80  90 100]


In [60]:
remove = [0,3,4]

np.delete(array,remove)

array([ 20,  30,  60,  70,  80,  90, 100])